kind: pipeline
name: default
steps:

  - name: build
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [dry-run-built]
      dry_run: true
    when:
      event:
      - push
      - pull_request

  - name: build_and_publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [latest]
    when:
      branch:
      - master
      event:
      - push

  - name: build_publish_and_tag_with_release_version
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      auto_tag: true
    when:
      branch:
      - release-test-branch
      event:
      - tag
      - push
